### ISSUE TITLE
Adding vSAN appliance models like Dell EMC VxRail systems

### ISSUE THREAD

**Issue by harikrishnant** [valdecircarvalho/awesome-vsan#2]
VxRail is a vSAN appliance model. We could add some references / pointers regarding:

* VxRail offerings and architecture
* Links to VxRail documentations / blogs
* VxRail tutorials
* Customer success stories
* VxRail Xperts list

What do you think #vCommunity?

**Comment by valdecircarvalho** [comment]
I like it! Send the links

**Comment by harikrishnant** [comment]
1. VxRail Product Page : 

https://www.dellemc.com/en-us/converged-infrastructure/vxrail/index.htm
https://shop.dellemc.com/en-us/Product-Family/VxRail-Products/Dell-EMC-VxRail-Appliance/p/VCE-VxRail

2. VxRail Appliance Techbook : 

https://www.dellemc.com/resources/en-us/asset/technical-guides-support-information/products/converged-infrastructure/h15104-vxrail-appliance-techbook.pdf

3. VxRail Quick Start Guide:

https://www.dellemc.com/resources/en-us/asset/technical-guides-support-information/products/converged-infrastructure/vxrail-quickstart-guide.pdf

4. VxRail Network Guide :

https://www.dellemc.com/en-us/collaterals/unauth/technical-guides-support-information/products/converged-infrastructure/h15300-vxrail-network-guide.pdf

5. VxRail Stretched Clusters Planning Guide : 

https://www.dellemc.com/en-us/collaterals/unauth/white-papers/products/converged-infrastructure/h15275-vxrail-planning-guide-virtual-san-stretched-cluster.pdf

6. VxRail vCenter Server Planning Guide : 

https://www.dellemc.com/en-us/collaterals/unauth/technical-guides-support-information/products/converged-infrastructure/h15844-vxrail-4-0-vcenter-server-pg.pdf

7. VxRail Xpress Sizer : 

https://mainstayadvisor.com/go/emc/vxrail/index.html

8. VxRail Customer Success Stories : 

https://www.dellemc.com/en-us/converged-infrastructure/customers/index.htm#customer=altalink&dropdownfilter1=vxrail

9. VxRail HOL : 

http://labs.hol.vmware.com/HOL/catalogs/lab/3786

10. Dell EMC VxRail DECN Community : 

https://community.emc.com/community/products/vxrail

11. VxRail Xpert Community : 

http://vxrail.is/xperts

**Comment by valdecircarvalho** [comment]
Hi!
Added a new section #VxRAIL with your links. Thank you
